name: Test Firestore Rules

on:
  workflow_dispatch:
  push:
    paths:
      - 'tests/**'
      - 'firestore.rules'

jobs:
  test:
    name: Test Firestore Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}       
          restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
      - name: Cache Firebase Emulator Binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install Firestore Rules Tests Dependencies
        run: npm ci
        working-directory: tests
      - name: Run Tests
        run: npm run test-firestore-security-rules
        working-directory: tests
